PEP8
jmptbl/python-zint pull request #2
Opened 2017-12-17 18:12 UTC by Cabalist

Hey there,

Thank you for this project it really saved me during a warehouse emergency last night.  I did some mild cleanup to the code.  Should have no functionality changes but just make it more PEP8-y....   

I really like the way you wrote the _fields_ declarations.   So simple and I've seen such ugly implementations using __new__().

2017-12-17 18:22 UTC, Cabalist commented
I added one more commit to make the README examples Python3 compatible.  The code itself works great in Python3 as long as you pass a bytes instead of a str.  The examples still work in Python2 as well.

2019-05-31 15:01 UTC, jmptbl approved these changes

2019-05-31 15:04 UTC, jmptbl requested changes
I'll merge the import changes, but the rest I do not like. Appreciate your feedback though!

2019-05-31 15:08 UTC, jmptbl commented
Since your PR contains a mix of changes that I like and dislike, I think it'll be easiest if I commit the parts that I like separately myself. Again, you contribution is greatly appreciated!

2019-05-31 15:08 UTC, closed without merging